#!/bin/bash

#to index the sacCer3 reference genome using bwa index command
bwa index sacCer3.fa

for SAMPLE in 09 11 23 24 27 31 35 39 62 63
do
	bwa mem -R "@RG\tID:${SAMPLE}\tSM:${SAMPLE}" -t 4 -o ${SAMPLE}.sam sacCer3.fa A01_${SAMPLE}.fastq
done

for SAMPLE in 09 11 23 24 27 31 35 39 62 63
do
	samtools sort -@4 -O bam -o ${SAMPLE}.bam ${SAMPLE}.sam
done

for SAMPLE in 09 11 23 24 27 31 35 39 62 63
do
	samtools index ${SAMPLE}.bam > ${SAMPLE}.bam.bai
done

freebayes -f sacCer3.fa --genotype-qualities 09.bam 11.bam 23.bam 24.bam 27.bam 31.bam 35.bam 39.bam 62.bam 63.bam | vcffilter -f "QUAL > 20" > results.vcf

vcfallelicprimitives -k -g results.vcf > allele.vcf

snpeff ann R64-1-1.99 results.vcf > var.vcf

